alert("you are chad!!!")
alert("yeah")
alert("really")
alert("you are!")
alert("no internet conection!")
alert("hahhahaha")
alert("LOL")
alert("Loading...")
alert("Loading...")
alert("WELCOME CHAD!!!")
